apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: hetzner-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.244.0.0/16
    services:
      cidrBlocks:
      - 10.245.0.0/16
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: hetzner-control-plane
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: HetznerCluster
    name: hetzner-cluster
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: hetzner-control-plane
  namespace: default
spec:
  replicas: 1
  version: v1.36.4
  machineTemplate:
    spec:
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: HCloudMachineTemplate
        name: flatcar-control-plane
  kubeadmConfigSpec:
    format: ignition
    users:
    - name: root
      sshAuthorizedKeys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK62bmiHlXJYTDvztBWnJ5Xik2RfuvK7D255T5jhx91F lieberlois@LuisLaptop
    initConfiguration:
      nodeRegistration:
        criSocket: /run/containerd/containerd.sock
        kubeletExtraArgs:
        - name: cloud-provider
          value: external
    joinConfiguration:
      nodeRegistration:
        criSocket: /run/containerd/containerd.sock
        kubeletExtraArgs:
        - name: cloud-provider
          value: external
    preKubeadmCommands:
    - export PATH=$PATH:/opt/bin
    - systemctl enable --now containerd
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: hetzner-cluster
  namespace: default
spec:
  controlPlaneEndpoint:
    host: ""
    port: 443
  controlPlaneRegions:
  - fsn1
  controlPlaneLoadBalancer:
    region: fsn1
  hcloudNetwork:
    cidrBlock: 10.0.0.0/16
    enabled: true
    subnetCidrBlock: 10.0.0.0/24
  hetznerSecretRef:
    name: hcloud
    key:
      hcloudToken: hcloud
      hetznerRobotUser: robot-user
      hetznerRobotPassword: robot-password
  sshKeys:
    hcloud:
    - name: hetzner-flatcar-key
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: flatcar-control-plane
  namespace: default
spec:
  template:
    spec:
      type: cpx22
      imageName: flatcar-stable-x86-v1.36.4
      sshKeys:
      - name: hetzner-flatcar-key
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: flatcar-worker-config
  namespace: default
spec:
  template:
    spec:
      format: ignition
      users:
      - name: root
        sshAuthorizedKeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK62bmiHlXJYTDvztBWnJ5Xik2RfuvK7D255T5jhx91F lieberlois@LuisLaptop
      joinConfiguration:
        nodeRegistration:
          criSocket: /run/containerd/containerd.sock
          kubeletExtraArgs:
          - name: cloud-provider
            value: external
      preKubeadmCommands:
      - export PATH=$PATH:/opt/bin
      - systemctl enable --now containerd
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: hetzner-worker-md
  namespace: default
spec:
  clusterName: hetzner-cluster
  replicas: 1
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        nodepool: worker
    spec:
      clusterName: hetzner-cluster
      version: v1.36.4
      failureDomain: fsn1
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: flatcar-worker-config
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: HCloudMachineTemplate
        name: flatcar-worker
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: flatcar-worker
  namespace: default
spec:
  template:
    spec:
      type: cpx22
      imageName: flatcar-stable-x86-v1.36.4
      sshKeys:
      - name: hetzner-flatcar-key
