apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: hetzner-cluster
  namespace: default
  labels:
    addons: enabled
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.244.0.0/16
    services:
      cidrBlocks:
      - 10.245.0.0/16
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: hetzner-control-plane
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: HetznerCluster
    name: hetzner-cluster