apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: hetzner-cluster
  namespace: default
spec:
  controlPlaneEndpoint:
    host: ""
    port: 443
  controlPlaneRegions:
  - fsn1
  controlPlaneLoadBalancer:
    region: fsn1
  hcloudNetwork:
    cidrBlock: 10.0.0.0/16
    enabled: true
    subnetCidrBlock: 10.0.0.0/24
  hetznerSecretRef:
    name: hcloud
    key:
      hcloudToken: hcloud
      hetznerRobotUser: robot-user
      hetznerRobotPassword: robot-password
  sshKeys:
    hcloud:
    - name: hetzner-flatcar-key