apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: flatcar-worker
  namespace: default
spec:
  template:
    spec:
      type: cpx22
      imageName: flatcar-stable-x86
      sshKeys:
      - name: hetzner-flatcar-key