apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: hetzner-control-plane
  namespace: default
spec:
  replicas: 1
  version: v1.36.4
  machineTemplate:
    spec:
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: HCloudMachineTemplate
        name: flatcar-control-plane
  kubeadmConfigSpec:
    format: ignition
    users:
    - name: root
      sshAuthorizedKeys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAgPVuRlet/qJl4KsKBI26n4l9oNp8nd/9hHXB07y27a capi-management-hetzner
    files:
    - content: |
        net.bridge.bridge-nf-call-iptables = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward = 1
        net.ipv4.conf.lxc*.rp_filter = 0
      owner: root:root
      path: /etc/sysctl.d/99-kubernetes.conf
      permissions: "0644"
    - content: |
        nameserver 1.1.1.1
        nameserver 1.0.0.1
      owner: root:root
      path: /etc/kubernetes/resolv.conf
      permissions: "0644"
    ignition:
      containerLinuxConfig:
        additionalConfig: |
          storage:
            links:
            - path: /etc/extensions/kubernetes.raw
              hard: false
              target: /opt/extensions/kubernetes/kubernetes-v1.36.4-x86-64.raw
            files:
            - path: /etc/sysupdate.kubernetes.d/kubernetes-v1.36.conf
              mode: 0644
              contents:
                remote:
                  url: https://extensions.flatcar.org/extensions/kubernetes/kubernetes-v1.36.conf
            - path: /etc/sysupdate.d/noop.conf
              mode: 0644
              contents:
                remote:
                  url: https://extensions.flatcar.org/extensions/noop.conf
            - path: /opt/extensions/kubernetes/kubernetes-v1.36.4-x86-64.raw
              contents:
                remote:
                  url: https://extensions.flatcar.org/extensions/kubernetes/kubernetes-v1.36.4-x86-64.raw
          systemd:
            units:
            - name: systemd-sysupdate.service
              dropins:
              - name: kubernetes.conf
                contents: |
                  [Service]
                  ExecStartPre=/usr/bin/sh -c "readlink --canonicalize /etc/extensions/kubernetes.raw > /tmp/kubernetes"
                  ExecStartPre=/usr/lib/systemd/systemd-sysupdate -C kubernetes update
                  ExecStartPost=/usr/bin/sh -c "readlink --canonicalize /etc/extensions/kubernetes.raw > /tmp/kubernetes-new"
                  ExecStartPost=/usr/bin/sh -c "if ! cmp --silent /tmp/kubernetes /tmp/kubernetes-new; then touch /run/reboot-required; fi"
            - name: systemd-sysupdate.timer
              enabled: false
            - name: kubeadm.service
              dropins:
              - name: 10-flatcar.conf
                contents: |
                  [Unit]
                  After=containerd.service
    initConfiguration:
      skipPhases:
      - addon/kube-proxy
      nodeRegistration:
        criSocket: /run/containerd/containerd.sock
        kubeletExtraArgs:
        - name: cloud-provider
          value: external
        - name: resolv-conf
          value: /etc/kubernetes/resolv.conf
    joinConfiguration:
      skipPhases:
      - addon/kube-proxy
      nodeRegistration:
        criSocket: /run/containerd/containerd.sock
        kubeletExtraArgs:
        - name: cloud-provider
          value: external
        - name: resolv-conf
          value: /etc/kubernetes/resolv.conf
